import Head from "next/head";

import {
  
  AiFillLinkedin,
  AiFillInstagram,
  AiFillGithub,
  
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/IMAGE 2023-05-11 10:35:33.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/Screenshot 2023-05-11 at 23.02.12.png";
import web2 from "../public/Screenshot 2023-05-11 at 23.02.51.png";
import web3 from "../public/Screenshot 2023-05-11 at 23.03.50.png";
import web4 from "../public/Screenshot 2023-05-11 at 23.10.10.png";





  

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">I. Isroilov</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                  
                      <a
                        className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                        href="https://acrobat.adobe.com/id/urn:aaid:sc:AP:030878de-d7b3-47b8-b5be-979d10e3cd2a"
                        target="_blank" rel="noreferrer"
                        
                      >
                        Resume
                      </a>
                      
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Isroilov Islomjon
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I`m Isroilov Islomjon, a frontend developer with a passion for creating captivating and user-friendly web interfaces. I strive to deliver exceptional projects that leave a lasting impact.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/IslamDEV007?tab=repositories" target="_blank" rel="noreferrer"><AiFillGithub /></a>
              <a href="linkedin.com/in/islomjon-isroilov-994312221" target="_blank" rel="noreferrer"><AiFillLinkedin/></a>
              <a href="https://www.instagram.com/isroilovislomjon1/" target="_blank" rel="noreferrer"><AiFillInstagram/></a>

            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved}   class="h-auto max-w-full rounded-lg"  alt="the user"/>
            </div>
          </div>
        </section>
        <section>
          
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} alt="design img"/>
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML/CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React.js</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="Coding picture" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML/CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React.js</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting}
                width={100}
                height={100}
                alt="consulting img"
                 />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in collaborating in a new project? Let&apos;s do it together
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML/CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">React.js</p>
              <p className="text-gray-800 py-1">NextJS</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a frontend developer,
               I&apos;ve learned needed skills for my career
              and created different interactive projects
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am open to new experiences and building new and amazing projects. 
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
          
           <div className="basis-1/3 flex-1 ">
           <a href="https://quizapp-react-project.netlify.app" target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="project-1"
              />
            </a>
              
            </div>
          
            
            <div className="basis-1/3 flex-1">
              <a href="https://hacker-news-api-react-project.netlify.app" target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="project-2"
              />
              </a>
             
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://findcocktail-api.netlify.app" target="_blank" rel="noreferrer">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="project-3"
              />
              </a>
             
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="project-4"
              />
            </div>
           
            
          </div>
        </section>
      </main>
    </div>
  );
}
